from __future__ import absolute_import

import mock

from flask import current_app

from changes.models.command import CommandType
from changes.models.jobplan import JobPlan
from changes.testutils import TestCase


class AutogeneratedJobTest(TestCase):
    @mock.patch('changes.models.project.Project.get_config')
    def test_autogenerated_commands(self, get_config):
        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.dependencies': {
                'encap': [
                    'package1',
                    'pkg-2',
                ]
            }
        }

        current_app.config['APT_SPEC'] = 'deb http://example.com/debian distribution component1'
        current_app.config['ENCAP_RSYNC_URL'] = 'rsync://example.com/encap/'

        project = self.create_project()
        plan = self.create_plan(project)
        option = self.create_option(
            item_id=plan.id,
            name='bazel.autogenerate',
            value='1',
        )
        build = self.create_build(project)
        job = self.create_job(build)
        jobplan = self.create_job_plan(job, plan)

        _, implementation = JobPlan.get_build_step_for_job(job.id)

        bazel_setup_expected = """#!/bin/bash -eux
echo "deb http://example.com/debian distribution component1" | sudo tee /etc/apt/sources.list.d/bazel-changes-autogen.list
sudo apt-get update || true
sudo apt-get install -y --force-yes bazel drte-v1 gcc unzip zip
""".strip()

        sync_encap_expected = """
sudo mkdir -p /usr/local/encap/
sudo rsync -a --delete rsync://example.com/encap/package1 /usr/local/encap/
sudo rsync -a --delete rsync://example.com/encap/pkg-2 /usr/local/encap/
""".strip()

        collect_tests_expected = """#!/bin/bash -eu
echo "deb http://example.com/debian distribution component1" | sudo tee /etc/apt/sources.list.d/bazel-changes-autogen.list > /dev/null 2>&1
(sudo apt-get update || true) > /dev/null 2>&1
sudo apt-get install -y --force-yes bazel drte-v1 gcc unzip zip python > /dev/null 2>&1
(bazel query 'tests(//aa/bb/cc/... + //aa/abc/...)' | python -c "import sys
import json


targets = sys.stdin.read().splitlines()
out = {
    'cmd': 'bazel test {test_names}',
    'tests': targets,
}
json.dump(out, sys.stdout)
") 2> /dev/null
""".strip()

        assert len(implementation.commands) == 3

        assert implementation.commands[0].type == CommandType.setup
        assert implementation.commands[0].script == bazel_setup_expected

        assert implementation.commands[1].type == CommandType.setup
        assert implementation.commands[1].script == sync_encap_expected

        assert implementation.commands[2].type == CommandType.collect_tests
        assert implementation.commands[2].script == collect_tests_expected
