from __future__ import absolute_import

import mock

from flask import current_app

from changes.models.command import CommandType
from changes.models.jobplan import JobPlan
from changes.testutils import TestCase


class AutogeneratedJobTest(TestCase):
    def _create_job_and_jobplan(self):
        current_app.config['APT_SPEC'] = 'deb http://example.com/debian distribution component1'
        current_app.config['ENCAP_RSYNC_URL'] = 'rsync://example.com/encap/'
        current_app.config['BAZEL_APT_PKGS'] = ['bazel']
        current_app.config['BAZEL_ROOT_PATH'] = '/bazel/root/path'

        project = self.create_project()
        plan = self.create_plan(project)
        option = self.create_option(
            item_id=plan.id,
            name='bazel.autogenerate',
            value='1',
        )
        build = self.create_build(project)
        job = self.create_job(build)
        jobplan = self.create_job_plan(job, plan)
        return job

    @mock.patch('changes.models.project.Project.get_config')
    def test_autogenerated_commands(self, get_config):
        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.dependencies': {
                'encap': [
                    'package1',
                    'pkg-2',
                ]
            },
            'bazel.exclude-tags': [],
            'bazel.cpus': 4,           # Default
            'bazel.mem': 8192,         # Default
        }

        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)

        bazel_setup_expected = """#!/bin/bash -eux
# Clean up any existing apt sources
sudo rm -rf /etc/apt/sources.list.d
# Overwrite apt sources
echo "deb http://example.com/debian distribution component1" | sudo tee /etc/apt/sources.list

# apt-get update, and try again if it fails first time
sudo apt-get -y update || sudo apt-get -y update
sudo apt-get install -y --force-yes bazel

/usr/bin/bazel --nomaster_blazerc --blazerc=/dev/null --output_user_root=/bazel/root/path --batch version
""".strip()

        sync_encap_expected = """
sudo mkdir -p /usr/local/encap/
sudo /usr/bin/rsync -a --delete rsync://example.com/encap/package1 /usr/local/encap/
sudo /usr/bin/rsync -a --delete rsync://example.com/encap/pkg-2 /usr/local/encap/
""".strip()

        collect_tests_expected = """#!/bin/bash -eu
# Clean up any existing apt sources
sudo rm -rf /etc/apt/sources.list.d >/dev/null 2>&1
# Overwrite apt sources
(echo "deb http://example.com/debian distribution component1" | sudo tee /etc/apt/sources.list) >/dev/null 2>&1

# apt-get update, and try again if it fails first time
(sudo apt-get -y update || sudo apt-get -y update) >/dev/null 2>&1
sudo apt-get install -y --force-yes bazel python >/dev/null 2>&1

(/usr/bin/bazel --nomaster_blazerc --blazerc=/dev/null --output_user_root=/bazel/root/path --batch query \
    'let t = tests(//aa/bb/cc/... + //aa/abc/...) in ($t )' | \
    python -c "import sys
import json


targets = sys.stdin.read().splitlines()
out = {
    'cmd': '/usr/bin/bazel --output_user_root=/bazel/root/path test --jobs=8 {test_names}',
    'tests': targets,
}
json.dump(out, sys.stdout)
") 2> /dev/null
""".strip()

        assert len(implementation.commands) == 3

        assert implementation.commands[0].type == CommandType.setup
        assert implementation.commands[0].script == bazel_setup_expected

        assert implementation.commands[1].type == CommandType.setup
        assert implementation.commands[1].script == sync_encap_expected

        assert implementation.commands[2].type == CommandType.collect_tests
        assert implementation.commands[2].script == collect_tests_expected

        assert implementation.artifact_search_path == '/bazel/root/path/bazel-testlogs/'
        assert implementation.artifacts == ['*.xml']

    @mock.patch('changes.models.project.Project.get_config')
    def test_autogenerated_commands_with_exclusions(self, get_config):
        get_config.return_value = {
            'bazel.targets': [
                '//foo/bar/baz/...',
                '//bar/bax/...',
            ],
            'bazel.exclude-tags': [
                'flaky',
                'another_tag',
            ],
            'bazel.cpus': 2,
            'bazel.mem': 1234,
        }

        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)

        assert implementation.resources['cpus'] == 2
        assert implementation.resources['mem'] == 1234

        collect_tests_expected = """#!/bin/bash -eu
# Clean up any existing apt sources
sudo rm -rf /etc/apt/sources.list.d >/dev/null 2>&1
# Overwrite apt sources
(echo "deb http://example.com/debian distribution component1" | sudo tee /etc/apt/sources.list) >/dev/null 2>&1

# apt-get update, and try again if it fails first time
(sudo apt-get -y update || sudo apt-get -y update) >/dev/null 2>&1
sudo apt-get install -y --force-yes bazel python >/dev/null 2>&1

(/usr/bin/bazel --nomaster_blazerc --blazerc=/dev/null --output_user_root=/bazel/root/path --batch query \
    'let t = tests(//foo/bar/baz/... + //bar/bax/...) in ($t except (attr("tags", "(\[| )flaky(\]|,)", $t)) except (attr("tags", "(\[| )another_tag(\]|,)", $t)))' | \
    python -c "import sys
import json


targets = sys.stdin.read().splitlines()
out = {
    'cmd': '/usr/bin/bazel --output_user_root=/bazel/root/path test --jobs=4 {test_names}',
    'tests': targets,
}
json.dump(out, sys.stdout)
") 2> /dev/null
""".strip()

        assert len(implementation.commands) == 3

        assert implementation.commands[0].type == CommandType.setup
        assert implementation.commands[1].type == CommandType.setup
        assert implementation.commands[2].type == CommandType.collect_tests
        assert implementation.commands[2].script == collect_tests_expected

    @mock.patch('changes.models.project.Project.get_config')
    def test_invalid_cpus(self, get_config):
        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.exclude-tags': [],
            'bazel.cpus': 0,           # 0 CPUs is not valid
            'bazel.mem': 8192,
        }

        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)
        assert implementation is None

        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.exclude-tags': [],
            'bazel.cpus': 2,           # Too many
            'bazel.mem': 8192,
        }

        current_app.config['MAX_CPUS_PER_EXECUTOR'] = 1
        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)
        assert implementation is None

    @mock.patch('changes.models.project.Project.get_config')
    def test_invalid_mems(self, get_config):
        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.exclude-tags': [],
            'bazel.cpus': 1,
            'bazel.mem': 1025,         # Too high
        }

        current_app.config['MIN_MEM_MB_PER_EXECUTOR'] = 1
        current_app.config['MAX_MEM_MB_PER_EXECUTOR'] = 10
        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)

        assert implementation is None

        get_config.return_value = {
            'bazel.targets': [
                '//aa/bb/cc/...',
                '//aa/abc/...',
            ],
            'bazel.exclude-tags': [],
            'bazel.cpus': 1,
            'bazel.mem': 1025,         # Too low
        }

        current_app.config['MIN_MEM_MB_PER_EXECUTOR'] = 2000
        current_app.config['MAX_MEM_MB_PER_EXECUTOR'] = 3000
        _, implementation = JobPlan.get_build_step_for_job(self._create_job_and_jobplan().id)

        assert implementation is None
