module.exports = function(grunt) {
  "use strict";
  grunt.loadNpmTasks("grunt-contrib-requirejs");
  grunt.loadNpmTasks("grunt-angular-templates");

  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    ngtemplates: {
      app: {
        src:  'partials/**/*.html',
        dest: 'static/js/generated/ngtemplates.js',
        options: {
          bootstrap: function(module, script) {
            // HACK: strip the 'use strict' that grunt-angular-templates/tasks/lib/compiler.js
            // adds so we have it once and in the right place
            var prefix = "  'use strict';" + grunt.util.linefeed;
            if (script.indexOf(prefix) == 0) {
              script = script.substr(prefix.length);
            }
            return "// generated by grunt-angular-templates\n\n" +
              "define(['app'], function(app) {\n" +
                prefix +
                "app.run(['$templateCache', function($templateCache) {\n" +
                   script + "\n" +
                 "}]);\n" +
              "});"
          }
        }
      }
    },
    requirejs: {
      compile: {
        options: {
          baseUrl: "js/",
          mainConfigFile: "static/js/main.js",
          appDir: "static/",
          dir: "static-built/",
          skipDirOptimize: true,
          generateSourceMaps: true,
          findNestedDependencies: true,
          preserveLicenseComments: false,
          removeCombined: true,
          modules: [
            {
              name: "main",
              exclude: ["vendor-angular", "vendor-jquery", "vendor-misc"]
            },
            {
              name: "vendor-angular"
            },
            {
              name: "vendor-jquery"
            },
            {
              name: "vendor-misc"
            }
          ],
          optimize: "uglify2",
          optimizeCss: "none",
          useSourceUrl: true,
          wrapShim: true
        }
      }
    }
  });

  grunt.registerTask('compile-static', ['ngtemplates', 'requirejs']);
};
