module.exports = function(grunt) {
  "use strict";
  grunt.loadNpmTasks("grunt-contrib-requirejs");
  grunt.loadNpmTasks("grunt-angular-templates");

  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    ngtemplates: {
      app: {
        src:  'partials/**/*.html',
        dest: 'static/js/generated/ngtemplates.js',
        options: {
          bootstrap: function(module, script) {
            // HACK: strip the 'use strict' that grunt-angular-templates/tasks/lib/compiler.js
            // adds so we have it once and in the right place
            var prefix = "  'use strict';" + grunt.util.linefeed;
            if (script.indexOf(prefix) == 0) {
              script = script.substr(prefix.length);
            }
            return "// generated by grunt-angular-templates\n\n" +
              "define(['app'], function(app) {\n" +
                prefix +
                "app.run(['$templateCache', function($templateCache) {\n" +
                   script + "\n" +
                 "}]);\n" +
              "});"
          }
        }
      }
    },
    requirejs: {
      compile1: {
        options: {
          baseUrl: "js/",
          mainConfigFile: "static/js/main.js",
          appDir: "static/",
          dir: "static-built/",
          skipDirOptimize: true,
          generateSourceMaps: true,
          findNestedDependencies: true,
          preserveLicenseComments: false,
          removeCombined: true,
          modules: [
            {
              name: "main",
              exclude: ["vendor-angular", "vendor-jquery", "vendor-misc"]
            },
            {
              name: "vendor-angular"
            },
            {
              name: "vendor-jquery"
            },
            {
              name: "vendor-misc"
            }
          ],
          optimize: "uglify2",
          optimizeCss: "none",
          useSourceUrl: true,
          wrapShim: true
        }
      },
      compile2: {
        options: {
          baseUrl: "webapp/",
          name: "entry", // assumes a production build using almond
          out: "webapp/dist/built.js",

          // the paths config attribute in entry.js uses URL paths (which are 
          // completely controlled by the flask app.) This attribute uses the
          // actual file locations on disk
          'paths': {
              'babel': '../static/vendor/requirejs-babel/babel-4.6.6.min',
              'classnames': '../static/vendor/classnames/index',
              'es6': '../static/vendor/requirejs-babel/es6',
              'moment': "../static/vendor/moment/min/moment.min",
              'react': '../static/vendor/react/react-with-addons',
              'react-dom': '../static/vendor/react/react-dom',
              'react_bootstrap': '../static/vendor/react-bootstrap/react-bootstrap',
              'requirejs': '../static/vendor/requirejs/require',
              'underscore': '../static/vendor/underscore/underscore',
              'uriJS': '../static/vendor/uri.js/src'
          },

          config: {
            'es6': {
              'optional': ['es7.objectRestSpread'],
            }
          },

          shim: {
            underscore: {
              exports: '_'
            },
          },

          // Increase the require.js load timeout threshold, since the ES6
          // compilation step in development mode often exceeds the default
          // 7-second threshold.
          waitSeconds: 15,

          'stubModules': ['es6', 'babel'],

          // uglify would cut the final file size by 50%, but make debugging 
          // more difficult. Not to mention that we rely on window.* globals 
          // a fair amount
          'optimize': 'none',

          // hmm..I've completely forgetten what this does
          'pragmasOnSave': {
              'excludeBabel': true
          }
        }
      }
    }
  });

  grunt.registerTask('compile-static', ['ngtemplates', 'requirejs']);
  grunt.registerTask('compile-reactjs', ['requirejs:compile2']);
};
