from sqlalchemy import literal
from changes.config import db
from changes.models.build import Build  # NOQA
from changes.models.jobplan import JobPlan
from changes.models.option import ItemOption


def contains_autogenerated_plan(build):
    """Returns true if any of the jobs in this build was created with an
    autogenerated jobplan.
    """
    # type: (Build)->bool
    contains = db.session.query(literal(True)).filter(
        ItemOption.query.join(
            JobPlan, JobPlan.plan_id == ItemOption.item_id,
        ).filter(
            ItemOption.name == 'bazel.autogenerate',
            ItemOption.value == '1',
            JobPlan.build_id == build.id,
        ).exists()
    ).scalar()
    return bool(contains)
