"""Add ItemOption

Revision ID: 1109e724859f
Revises: 3d9067f21201
Create Date: 2013-12-18 16:50:30.093508

"""

# revision identifiers, used by Alembic.
revision = '1109e724859f'
down_revision = '3d9067f21201'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'itemoption',
        sa.Column('id', sa.GUID(), nullable=False),
        sa.Column('item_id', sa.GUID(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_id', 'name', name='unq_itemoption_name')
    )


def downgrade():
    op.drop_table('itemoption')
