"""Add Build.revision-sha

Revision ID: 14491da59392
Revises: 32274e97552
Create Date: 2013-10-29 11:43:47.367799

"""

# revision identifiers, used by Alembic.
revision = '14491da59392'
down_revision = '32274e97552'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('revision_sha', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'revision_sha')
    ### end Alembic commands ###
