"""Add RepositoryOption

Revision ID: 152c9c780e
Revises: 4d302aa44bc8
Create Date: 2013-11-26 17:48:21.180630

"""

# revision identifiers, used by Alembic.
revision = '152c9c780e'
down_revision = '4d302aa44bc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositoryoption',
    sa.Column('id', sa.GUID(), nullable=False),
    sa.Column('repository_id', sa.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id','name', name='unq_repositoryoption_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repositoryoption')
    ### end Alembic commands ###
