"""Add Change.message

Revision ID: 15579762e546
Revises: 46d3e189a87c
Create Date: 2013-09-30 12:00:55.279871

"""

# revision identifiers, used by Alembic.
revision = '15579762e546'
down_revision = '46d3e189a87c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'message')
    ### end Alembic commands ###
