"""Add Project.slug

Revision ID: 179ec3e09d33
Revises: 5837208327ff
Create Date: 2013-09-23 15:19:20.880310

"""

# revision identifiers, used by Alembic.
revision = '179ec3e09d33'
down_revision = '5837208327ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slug', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'slug')
    ### end Alembic commands ###
