"""Add various Build indexes

Revision ID: 18c045b75331
Revises: d324e8fc580
Create Date: 2013-11-04 17:14:33.455855

"""

# revision identifiers, used by Alembic.
revision = '18c045b75331'
down_revision = 'd324e8fc580'

from alembic import op


def upgrade():
    op.create_index('idx_build_project_id', 'build', ['project_id'])
    op.create_index('idx_build_repository_id', 'build', ['repository_id'])
    op.create_index('idx_build_author_id', 'build', ['author_id'])
    op.create_index('idx_build_patch_id', 'build', ['patch_id'])
    op.create_index('idx_build_change_id', 'build', ['change_id'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
