"""Add Build.cause and Buld.parent

Revision ID: 1b53d33197bf
Revises: 2b8459f1e2d6
Create Date: 2013-10-25 14:33:55.401260

"""

# revision identifiers, used by Alembic.
revision = '1b53d33197bf'
down_revision = '2b8459f1e2d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('cause', sa.Enum(), server_default='0', nullable=False))
    op.add_column('build', sa.Column('parent', sa.GUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'parent')
    op.drop_column('build', 'cause')
    ### end Alembic commands ###
