"""Add patch model

Revision ID: 2018cb70b484
Revises: 296665c60a0a
Create Date: 2013-09-23 11:36:51.982371

"""

# revision identifiers, used by Alembic.
revision = '2018cb70b484'
down_revision = '296665c60a0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch',
    sa.Column('id', sa.GUID(), nullable=False),
    sa.Column('repository_id', sa.GUID(), nullable=False),
    sa.Column('project_id', sa.GUID(), nullable=False),
    sa.Column('parent_revision_sha', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('diff', sa.LargeBinary(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'build', sa.Column('patch_id', sa.GUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'build', 'patch_id')
    op.drop_table('patch')
    ### end Alembic commands ###
