"""Add Repository.last_update, last_update_attempt

Revision ID: 215db24a630a
Revises: 208224023555
Create Date: 2013-11-25 15:41:16.798396

"""

# revision identifiers, used by Alembic.
revision = '215db24a630a'
down_revision = '208224023555'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('repository', sa.Column('last_update_attempt', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'last_update_attempt')
    op.drop_column('repository', 'last_update')
    ### end Alembic commands ###
