"""Add build.date_modified

Revision ID: 2585e43465a0
Revises: 4cbcf521fbd
Create Date: 2013-10-18 13:36:04.064521

"""

# revision identifiers, used by Alembic.
revision = '2585e43465a0'
down_revision = '4cbcf521fbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('date_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'date_modified')
    ### end Alembic commands ###
