"""Add Patch.message

Revision ID: 266ce4ec0bac
Revises: cbc0788a11
Create Date: 2013-10-01 18:19:45.608620

"""

# revision identifiers, used by Alembic.
revision = '266ce4ec0bac'
down_revision = 'cbc0788a11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patch', sa.Column('message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patch', 'message')
    ### end Alembic commands ###
