"""Add Build.target

Revision ID: 2d8acbec66df
Revises: 5aad6f742b77
Create Date: 2013-11-11 17:07:11.624071

"""

# revision identifiers, used by Alembic.
revision = '2d8acbec66df'
down_revision = '5aad6f742b77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('target', sa.String(length=128), nullable=True))
    op.drop_column('build', u'parent_revision_sha')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column(u'parent_revision_sha', sa.VARCHAR(length=40), nullable=True))
    op.drop_column('build', 'target')
    ### end Alembic commands ###
