"""Build.parent -> Build.parent_id

Revision ID: 32274e97552
Revises: 1b53d33197bf
Create Date: 2013-10-25 15:41:21.120737

"""

# revision identifiers, used by Alembic.
revision = '32274e97552'
down_revision = '1b53d33197bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('parent_id', sa.GUID(), nullable=True))
    op.drop_column('build', u'parent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column(u'parent', postgresql.UUID(), nullable=True))
    op.drop_column('build', 'parent_id')
    ### end Alembic commands ###
