"""Add Revision.parents

Revision ID: 33693f38fd96
Revises: 334bbae691d9
Create Date: 2013-10-06 23:22:11.827598

"""

# revision identifiers, used by Alembic.
revision = '33693f38fd96'
down_revision = '334bbae691d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('parents', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'parents')
    ### end Alembic commands ###
