"""Optional parent_revision_sha

Revision ID: 346c011ca77a
Revises: 2d8acbec66df
Create Date: 2013-11-11 17:08:40.087545

"""

# revision identifiers, used by Alembic.
revision = '346c011ca77a'
down_revision = '2d8acbec66df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch', 'parent_revision_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patch', 'parent_revision_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    ### end Alembic commands ###
