"""Drop ProjectPlan table

Revision ID: 36d7c98ddfee
Revises: 12569fada93
Create Date: 2014-10-14 11:25:48.151275

"""

# revision identifiers, used by Alembic.
revision = '36d7c98ddfee'
down_revision = '12569fada93'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_plan')


def downgrade():
    raise NotImplementedError
