"""Add PhabricatorDiff

Revision ID: 3768db8af6ea
Revises: 36d7c98ddfee
Create Date: 2014-10-31 16:06:52.277238

"""

# revision identifiers, used by Alembic.
revision = '3768db8af6ea'
down_revision = '36d7c98ddfee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'phabricatordiff',
        sa.Column('id', sa.GUID(), nullable=False),
        sa.Column('diff_id', sa.Integer(), nullable=True),
        sa.Column('revision_id', sa.Integer(), nullable=True),
        sa.Column('source_id', sa.GUID(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('diff_id')
    )


def downgrade():
    op.drop_table('phabricatordiff')
