"""Add Change.date_modified

Revision ID: 3ab6b0898a24
Revises: 48e38818132c
Create Date: 2013-09-30 17:07:12.368146

"""

# revision identifiers, used by Alembic.
revision = '3ab6b0898a24'
down_revision = '48e38818132c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('date_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'date_modified')
    ### end Alembic commands ###
