"""Add various TestGroup indexes

Revision ID: 3bef10ab5088
Revises: fd1a52fe89f
Create Date: 2013-11-04 17:10:52.057285

"""

# revision identifiers, used by Alembic.
revision = '3bef10ab5088'
down_revision = 'fd1a52fe89f'

from alembic import op


def upgrade():
    op.create_index('idx_testgroup_project_id', 'testgroup', ['project_id'])
    op.create_index('idx_testgroup_suite_id', 'testgroup', ['suite_id'])
    op.create_index('idx_testgroup_parent_id', 'testgroup', ['parent_id'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
