"""Add Build.data

Revision ID: 3d9bb600278d
Revises: 2585e43465a0
Create Date: 2013-10-18 14:42:22.768476

"""

# revision identifiers, used by Alembic.
revision = '3d9bb600278d'
down_revision = '2585e43465a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('data', sa.JSONEncodedDict(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'data')
    ### end Alembic commands ###
