"""Add BuildPhase

Revision ID: 4276d58dd1e6
Revises: 2596f21c6f58
Create Date: 2014-02-24 14:06:16.379028

"""

# revision identifiers, used by Alembic.
revision = '4276d58dd1e6'
down_revision = '2596f21c6f58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildphase',
        sa.Column('id', sa.GUID(), nullable=False),
        sa.Column('build_id', sa.GUID(), nullable=False),
        sa.Column('project_id', sa.GUID(), nullable=False),
        sa.Column('label', sa.String(length=128), nullable=False),
        sa.Column('status', sa.Enum(), server_default='0', nullable=False),
        sa.Column('result', sa.Enum(), server_default='0', nullable=False),
        sa.Column('order', sa.Integer(), server_default='0', nullable=False),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('date_started', sa.DateTime(), nullable=True),
        sa.Column('date_finished', sa.DateTime(), nullable=True),
        sa.Column('date_created', sa.DateTime(), server_default='now()', nullable=False),
        sa.ForeignKeyConstraint(['build_id'], ['build.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('build_id', 'label', name='unq_buildphase_key')
    )


def downgrade():
    op.drop_table('buildphase')
