"""Add TestGroup.num_leaves

Revision ID: 4640ecd97c82
Revises: 48a922151dd4
Create Date: 2013-11-08 13:11:18.802332

"""

# revision identifiers, used by Alembic.
revision = '4640ecd97c82'
down_revision = '48a922151dd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testgroup', sa.Column('num_leaves', sa.Integer(), nullable=False, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testgroup', 'num_leaves')
    ### end Alembic commands ###
