"""Add Build.message

Revision ID: 48e38818132c
Revises: 15579762e546
Create Date: 2013-09-30 13:22:09.406952

"""

# revision identifiers, used by Alembic.
revision = '48e38818132c'
down_revision = '15579762e546'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'message')
    ### end Alembic commands ###
