"""Add Build.author

Revision ID: 4c60e96c6874
Revises: 4e03cae8d0a2
Create Date: 2013-09-24 02:40:59.200521

"""

# revision identifiers, used by Alembic.
revision = '4c60e96c6874'
down_revision = '4e03cae8d0a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('author_id', sa.GUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'author_id')
    ### end Alembic commands ###
