"""Add additional revision data

Revision ID: 4d302aa44bc8
Revises: 215db24a630a
Create Date: 2013-11-26 16:20:59.454360

"""

# revision identifiers, used by Alembic.
revision = '4d302aa44bc8'
down_revision = '215db24a630a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('committer_id', sa.GUID(), nullable=True))
    op.add_column('revision', sa.Column('date_committed', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'date_committed')
    op.drop_column('revision', 'committer_id')
    ### end Alembic commands ###
