"""Support nullable parent_revision_sha

Revision ID: 52394fd42158
Revises: 4c60e96c6874
Create Date: 2013-09-24 02:41:39.983685

"""

# revision identifiers, used by Alembic.
revision = '52394fd42158'
down_revision = '4c60e96c6874'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'parent_revision_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'parent_revision_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    ### end Alembic commands ###
