"""Initial schemas

Revision ID: 9cc87c1ab97
Revises: None
Create Date: 2013-09-20 20:21:17.846522

"""

# revision identifiers, used by Alembic.
revision = '9cc87c1ab97'
down_revision = None

from alembic import op
import sqlalchemy as sa
from buildbox.db.types.guid import GUID


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('author',
    sa.Column('author_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('project',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.repository_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('revision',
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('revision_id', GUID(), nullable=False),
    sa.Column('author_id', GUID(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.repository_id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'revision_id')
    )
    op.create_table('build',
    sa.Column('build_id', GUID(), nullable=False),
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('parent_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.repository_id'], ),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_table('phase',
    sa.Column('phase_id', GUID(), nullable=False),
    sa.Column('build_id', GUID(), nullable=False),
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.build_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.repository_id'], ),
    sa.PrimaryKeyConstraint('phase_id')
    )
    op.create_table('step',
    sa.Column('step_id', GUID(), nullable=False),
    sa.Column('phase_id', GUID(), nullable=False),
    sa.Column('build_id', GUID(), nullable=False),
    sa.Column('repository_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.build_id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.phase_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.repository_id'], ),
    sa.PrimaryKeyConstraint('step_id', 'phase_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('phase')
    op.drop_table('build')
    op.drop_table('revision')
    op.drop_table('project')
    op.drop_table('author')
    op.drop_table('repository')
    ### end Alembic commands ###
