"""Remove Change.date_finished

Revision ID: cbc0788a11
Revises: 1e2d7f571919
Create Date: 2013-09-30 22:10:22.247890

"""

# revision identifiers, used by Alembic.
revision = 'cbc0788a11'
down_revision = '1e2d7f571919'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', u'date_finished')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column(u'date_finished', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
