"""Add Change model

Revision ID: cd427091f31
Revises: 4d0bd81fb144
Create Date: 2013-09-27 10:51:39.514337

"""

# revision identifiers, used by Alembic.
revision = 'cd427091f31'
down_revision = '4d0bd81fb144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change',
    sa.Column('id', sa.GUID(), nullable=False),
    sa.Column('hash', sa.String(length=40), nullable=False),
    sa.Column('repository_id', sa.GUID(), nullable=False),
    sa.Column('project_id', sa.GUID(), nullable=False),
    sa.Column('revision_sha', sa.String(length=40), nullable=True),
    sa.Column('parent_revision_sha', sa.String(length=40), nullable=True),
    sa.Column('author_id', sa.GUID(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['repository_id', 'parent_revision_sha'], ['revision.repository_id', 'revision.sha'], ),
    sa.ForeignKeyConstraint(['repository_id', 'revision_sha'], ['revision.repository_id', 'revision.sha'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.add_column(u'build', sa.Column('change_id', sa.GUID(), nullable=True))
    op.add_column(u'patch', sa.Column('change_id', sa.GUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'patch', 'change_id')
    op.drop_column(u'build', 'change_id')
    op.drop_table('change')
    ### end Alembic commands ###
