"""Add various TestSuite indexes

Revision ID: d324e8fc580
Revises: 3bef10ab5088
Create Date: 2013-11-04 17:12:09.353301

"""

# revision identifiers, used by Alembic.
revision = 'd324e8fc580'
down_revision = '3bef10ab5088'

from alembic import op


def upgrade():
    op.create_index('idx_testsuite_project_id', 'testsuite', ['project_id'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
