"""Add various test indexes

Revision ID: fd1a52fe89f
Revises: 5177cfff57d7
Create Date: 2013-11-04 17:03:03.005904

"""

# revision identifiers, used by Alembic.
revision = 'fd1a52fe89f'
down_revision = '5177cfff57d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
